services:
  mysql:
    image: mysql:latest  # Use uma versão estável do MySQL (8.0 ou superior)
    container_name: mysql_knex
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      TZ: America/Sao_Paulo
    volumes:
      - /mnt/d/MySQLDBData/mysql_knex:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped